/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package acessoCarregamento;


import br.com.conexao.dal.ModuloConexao;
//import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Igor
 */
public class TelaLogin extends javax.swing.JFrame {

    
    
    //usando a variável de conexão do DAL
    Connection conexao = null;
    //criando variáveis especiais para conexão com o banco de dados
    //Prepared Statement e ResultSet são fremework do pacote java.sql
    //serve para preparar e executar as instrução SQL
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void logar() {
        String sql = "select * from Condominiologin where Login=? and Senha=?";
        try {
            /* as linhas abaixo preparam a consulta ao banco em função do
            que foi digitado nas caixas de texto. o ? é substituido pelo
            conteúdo das variáveis. */

            pst = conexao.prepareStatement(sql);
            pst.setString(1, texusuario.getText());
            pst.setString(2, pasUsuario.getText());
            // a linha abaixo executa a query
            rs = pst.executeQuery();
            // se existir usuario e senha loga ao sistema
            if (rs.next()) {
                TelaPrincipal tel = new TelaPrincipal();
                tel.setVisible(true);
                 
                //a linha abaixo obtem o conteudo do campo perfil da tabela mrsystem, também a posição da tabela e coluna
                //String perfil = rs.getString(8);
                // System.out.println(perfil);
                // estrtura abaixo faz o trataento do perfil do usuário
              
            } else {
                JOptionPane.showMessageDialog(null, "Usuário se senha é inválido(s)");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Nadas1");
        }
    }
    
    public TelaLogin() {
        initComponents();
        conexao = ModuloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        texusuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pasUsuario = new javax.swing.JPasswordField();
        btnacessar1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setText("Login:");

        texusuario.setText("Inseri o login de usuário");
        texusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texusuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Senha:");

        pasUsuario.setText("jPasswordField2");
        pasUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasUsuarioActionPerformed(evt);
            }
        });

        btnacessar1.setForeground(new java.awt.Color(255, 255, 255));
        btnacessar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/img_Login.png"))); // NOI18N
        btnacessar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnacessar1ActionPerformed(evt);
            }
        });

        jButton1.setText("Termo de Uso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 153, 255));
        jLabel3.setText("Seja Bem Vindo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(texusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(pasUsuario)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(btnacessar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel3)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(texusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(pasUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnacessar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void texusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texusuarioActionPerformed

    private void pasUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasUsuarioActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_pasUsuarioActionPerformed

    private void btnacessar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnacessar1ActionPerformed
        // TODO add your handling code here:
      
      // String tex = texusuario.getText().toUpperCase();
      // String senha = pasUsuario.getText();
        logar();
       
       // TelaPrincipal tel = new TelaPrincipal();
       // tel.setVisible(true);
     
    }//GEN-LAST:event_btnacessar1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        TermoUso termo = new TermoUso();
        termo.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacessar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPasswordField pasUsuario;
    private javax.swing.JTextField texusuario;
    // End of variables declaration//GEN-END:variables
}

